version: "3.4"

services:
  redis:
    image: redis
    ports:
      - 6379:6379
    networks:
      - refinitiv
  calculatorserver:
    depends_on:
      - redis
    image: calculatorserver
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 3000:3000
    networks:
      - refinitiv
networks:
  refinitiv:
